// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by Openvia.AvroSchemaGenerator, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SchemaRegistry
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Asimplelogmessage.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Openvia.AvroSchemaGenerator", "1.11.1")]
	public partial class AvroLogMessage : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""AvroLogMessage"",""doc"":""Asimplelogmessage."",""namespace"":""SchemaRegistry"",""fields"":[{""name"":""Severity"",""type"":{""type"":""enum"",""name"":""LogLevel"",""doc"":""Enumeratesthesetofallowableloglevels."",""namespace"":""SchemaRegistry"",""symbols"":[""None"",""Verbose"",""Info"",""Warning"",""Error""]}}]}");
		private SchemaRegistry.LogLevel _Severity;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AvroLogMessage._SCHEMA;
			}
		}
		public SchemaRegistry.LogLevel Severity
		{
			get
			{
				return this._Severity;
			}
			set
			{
				this._Severity = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Severity;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Severity = (SchemaRegistry.LogLevel)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
