// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by Openvia.AvroSchemaGenerator, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SchemaRegistry
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Enumeratesthesetofallowableloglevels.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Openvia.AvroSchemaGenerator", "1.11.1")]
	public enum LogLevel
	{
		None,
		Verbose,
		Info,
		Warning,
		Error,
	}
}
